// Code generated by entc, DO NOT EDIT.

package message

import (
	"fmt"
)

const (
	// Label holds the string label denoting the message type in the database.
	Label = "message"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldType holds the string denoting the type field in the database.
	FieldType = "type"
	// FieldAction holds the string denoting the action field in the database.
	FieldAction = "action"
	// FieldMessage holds the string denoting the message field in the database.
	FieldMessage = "message"
	// FieldAutoRemove holds the string denoting the auto_remove field in the database.
	FieldAutoRemove = "auto_remove"
	// FieldAutoRemoveTime holds the string denoting the auto_remove_time field in the database.
	FieldAutoRemoveTime = "auto_remove_time"
	// Table holds the table name of the message in the database.
	Table = "messages"
)

// Columns holds all SQL columns for message fields.
var Columns = []string{
	FieldID,
	FieldType,
	FieldAction,
	FieldMessage,
	FieldAutoRemove,
	FieldAutoRemoveTime,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultType holds the default value on creation for the "type" field.
	DefaultType int
	// DefaultMessage holds the default value on creation for the "message" field.
	DefaultMessage string
	// DefaultAutoRemove holds the default value on creation for the "auto_remove" field.
	DefaultAutoRemove bool
	// DefaultAutoRemoveTime holds the default value on creation for the "auto_remove_time" field.
	DefaultAutoRemoveTime int
)

// Action defines the type for the "action" enum field.
type Action string

// Action values.
const (
	ActionWelcome   Action = "welcome"
	ActionStatistic Action = "statistic"
)

func (a Action) String() string {
	return string(a)
}

// ActionValidator is a validator for the "action" field enum values. It is called by the builders before save.
func ActionValidator(a Action) error {
	switch a {
	case ActionWelcome, ActionStatistic:
		return nil
	default:
		return fmt.Errorf("message: invalid enum value for action field: %q", a)
	}
}
