// Code generated by entc, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// CommandsColumns holds the columns for the "commands" table.
	CommandsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
	}
	// CommandsTable holds the schema information for the "commands" table.
	CommandsTable = &schema.Table{
		Name:       "commands",
		Columns:    CommandsColumns,
		PrimaryKey: []*schema.Column{CommandsColumns[0]},
	}
	// MessagesColumns holds the columns for the "messages" table.
	MessagesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "type", Type: field.TypeInt, Default: 0},
		{Name: "action", Type: field.TypeEnum, Enums: []string{"welcome", "statistic"}},
		{Name: "message", Type: field.TypeString, Default: ""},
		{Name: "auto_remove", Type: field.TypeBool, Default: false},
		{Name: "auto_remove_time", Type: field.TypeInt, Default: 30},
		{Name: "enable", Type: field.TypeBool, Default: false},
	}
	// MessagesTable holds the schema information for the "messages" table.
	MessagesTable = &schema.Table{
		Name:       "messages",
		Columns:    MessagesColumns,
		PrimaryKey: []*schema.Column{MessagesColumns[0]},
	}
	// StatisticsColumns holds the columns for the "statistics" table.
	StatisticsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "first_name", Type: field.TypeString, Default: ""},
		{Name: "lat_name", Type: field.TypeString, Default: ""},
		{Name: "user_name", Type: field.TypeString, Default: ""},
		{Name: "from_user", Type: field.TypeInt, Default: 0},
		{Name: "channel_id", Type: field.TypeInt64, Default: 0},
		{Name: "user_id", Type: field.TypeInt, Default: 0},
		{Name: "join_time", Type: field.TypeTime},
		{Name: "invited", Type: field.TypeInt64, Default: 0},
		{Name: "message", Type: field.TypeInt64, Default: 0},
		{Name: "last_message", Type: field.TypeTime},
	}
	// StatisticsTable holds the schema information for the "statistics" table.
	StatisticsTable = &schema.Table{
		Name:       "statistics",
		Columns:    StatisticsColumns,
		PrimaryKey: []*schema.Column{StatisticsColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		CommandsTable,
		MessagesTable,
		StatisticsTable,
	}
)

func init() {
}
