// Code generated by entc, DO NOT EDIT.

package statistic

const (
	// Label holds the string label denoting the statistic type in the database.
	Label = "statistic"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldFirstName holds the string denoting the first_name field in the database.
	FieldFirstName = "first_name"
	// FieldLatName holds the string denoting the lat_name field in the database.
	FieldLatName = "lat_name"
	// FieldUserName holds the string denoting the user_name field in the database.
	FieldUserName = "user_name"
	// FieldFromUser holds the string denoting the from_user field in the database.
	FieldFromUser = "from_user"
	// FieldChannelID holds the string denoting the channel_id field in the database.
	FieldChannelID = "channel_id"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldJoinTime holds the string denoting the join_time field in the database.
	FieldJoinTime = "join_time"
	// FieldInvited holds the string denoting the invited field in the database.
	FieldInvited = "invited"
	// FieldMessage holds the string denoting the message field in the database.
	FieldMessage = "message"
	// FieldLastMessage holds the string denoting the last_message field in the database.
	FieldLastMessage = "last_message"
	// Table holds the table name of the statistic in the database.
	Table = "statistics"
)

// Columns holds all SQL columns for statistic fields.
var Columns = []string{
	FieldID,
	FieldFirstName,
	FieldLatName,
	FieldUserName,
	FieldFromUser,
	FieldChannelID,
	FieldUserID,
	FieldJoinTime,
	FieldInvited,
	FieldMessage,
	FieldLastMessage,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultFirstName holds the default value on creation for the "first_name" field.
	DefaultFirstName string
	// DefaultLatName holds the default value on creation for the "lat_name" field.
	DefaultLatName string
	// DefaultUserName holds the default value on creation for the "user_name" field.
	DefaultUserName string
	// DefaultFromUser holds the default value on creation for the "from_user" field.
	DefaultFromUser int
	// DefaultChannelID holds the default value on creation for the "channel_id" field.
	DefaultChannelID int64
	// DefaultUserID holds the default value on creation for the "user_id" field.
	DefaultUserID int
	// DefaultJoinTime holds the default value on creation for the "join_time" field.
	DefaultJoinTime int64
	// DefaultInvited holds the default value on creation for the "invited" field.
	DefaultInvited int64
	// DefaultMessage holds the default value on creation for the "message" field.
	DefaultMessage int64
	// DefaultLastMessage holds the default value on creation for the "last_message" field.
	DefaultLastMessage int64
)
