// Code generated by entc, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/godcong/telebot/database/ent/message"
	"github.com/godcong/telebot/database/ent/schema"
	"github.com/godcong/telebot/database/ent/statistic"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	messageFields := schema.Message{}.Fields()
	_ = messageFields
	// messageDescType is the schema descriptor for type field.
	messageDescType := messageFields[0].Descriptor()
	// message.DefaultType holds the default value on creation for the type field.
	message.DefaultType = messageDescType.Default.(int)
	// messageDescMessage is the schema descriptor for message field.
	messageDescMessage := messageFields[2].Descriptor()
	// message.DefaultMessage holds the default value on creation for the message field.
	message.DefaultMessage = messageDescMessage.Default.(string)
	// messageDescAutoRemove is the schema descriptor for auto_remove field.
	messageDescAutoRemove := messageFields[3].Descriptor()
	// message.DefaultAutoRemove holds the default value on creation for the auto_remove field.
	message.DefaultAutoRemove = messageDescAutoRemove.Default.(bool)
	// messageDescAutoRemoveTime is the schema descriptor for auto_remove_time field.
	messageDescAutoRemoveTime := messageFields[4].Descriptor()
	// message.DefaultAutoRemoveTime holds the default value on creation for the auto_remove_time field.
	message.DefaultAutoRemoveTime = messageDescAutoRemoveTime.Default.(int)
	// messageDescEnable is the schema descriptor for enable field.
	messageDescEnable := messageFields[5].Descriptor()
	// message.DefaultEnable holds the default value on creation for the enable field.
	message.DefaultEnable = messageDescEnable.Default.(bool)
	statisticFields := schema.Statistic{}.Fields()
	_ = statisticFields
	// statisticDescFirstName is the schema descriptor for first_name field.
	statisticDescFirstName := statisticFields[0].Descriptor()
	// statistic.DefaultFirstName holds the default value on creation for the first_name field.
	statistic.DefaultFirstName = statisticDescFirstName.Default.(string)
	// statisticDescLatName is the schema descriptor for lat_name field.
	statisticDescLatName := statisticFields[1].Descriptor()
	// statistic.DefaultLatName holds the default value on creation for the lat_name field.
	statistic.DefaultLatName = statisticDescLatName.Default.(string)
	// statisticDescUserName is the schema descriptor for user_name field.
	statisticDescUserName := statisticFields[2].Descriptor()
	// statistic.DefaultUserName holds the default value on creation for the user_name field.
	statistic.DefaultUserName = statisticDescUserName.Default.(string)
	// statisticDescFromUser is the schema descriptor for from_user field.
	statisticDescFromUser := statisticFields[3].Descriptor()
	// statistic.DefaultFromUser holds the default value on creation for the from_user field.
	statistic.DefaultFromUser = statisticDescFromUser.Default.(int)
	// statisticDescChannelID is the schema descriptor for channel_id field.
	statisticDescChannelID := statisticFields[4].Descriptor()
	// statistic.DefaultChannelID holds the default value on creation for the channel_id field.
	statistic.DefaultChannelID = statisticDescChannelID.Default.(int64)
	// statisticDescUserID is the schema descriptor for user_id field.
	statisticDescUserID := statisticFields[5].Descriptor()
	// statistic.DefaultUserID holds the default value on creation for the user_id field.
	statistic.DefaultUserID = statisticDescUserID.Default.(int)
	// statisticDescJoinTime is the schema descriptor for join_time field.
	statisticDescJoinTime := statisticFields[6].Descriptor()
	// statistic.DefaultJoinTime holds the default value on creation for the join_time field.
	statistic.DefaultJoinTime = statisticDescJoinTime.Default.(func() time.Time)
	// statisticDescInvited is the schema descriptor for invited field.
	statisticDescInvited := statisticFields[7].Descriptor()
	// statistic.DefaultInvited holds the default value on creation for the invited field.
	statistic.DefaultInvited = statisticDescInvited.Default.(int64)
	// statisticDescMessage is the schema descriptor for message field.
	statisticDescMessage := statisticFields[8].Descriptor()
	// statistic.DefaultMessage holds the default value on creation for the message field.
	statistic.DefaultMessage = statisticDescMessage.Default.(int64)
	// statisticDescLastMessage is the schema descriptor for last_message field.
	statisticDescLastMessage := statisticFields[9].Descriptor()
	// statistic.DefaultLastMessage holds the default value on creation for the last_message field.
	statistic.DefaultLastMessage = statisticDescLastMessage.Default.(func() time.Time)
}
