// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Command is the predicate function for command builders.
type Command func(*sql.Selector)

// Message is the predicate function for message builders.
type Message func(*sql.Selector)

// Statistic is the predicate function for statistic builders.
type Statistic func(*sql.Selector)
